### PR TITLE
Add rbenv package

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by bucaran** [comment]
Hey @hauleth 

I am confused about this part of the plugin:

```fish
...
  switch "$command"
  case rehash shell update use
    eval (rbenv "sh-$command" $argv)
...
```

Why do you need to eval the command?

Also, why can't you simply `source  (rbenv init - | psub)` which is what I have in my `init.fish`?

One more thing, why are you using `setenv` if fish has `set -x`, or just `set` if you know the variable is already exported?

**Comment by hauleth** [comment]
I pasted what `rbenv init -` is generating because on my machine `source
(rbenv init - | psub)` was causing weird errors. Maybe I was doing
something wrong, but still. `setenv` is function that do the same as `set
-gx` so this isn't a problem (rbenv is also using this syntax). Feel free
to create pull request if you found way to fix issue with `psub` (I really
would love if I could do this that way).

--
Łukasz Niemier <lukasz@niemier.pl>
http://lukasz.niemier.pl

2015-05-26 21:21 GMT+02:00 Jorge Bucaran <notifications@github.com>:

**Comment by bucaran** [comment]
@hauleth I did some research, you actually came up in several searches so I'll grant you the `rbenv` on fish expert status :smile: 

One thing is the following appears to be not necessary if you already `set -gx RBENV_SHELL fish`.

```fish
  switch "$command"
  case rehash shell update use
    eval (rbenv "sh-$command" $argv)
  case '*'
    command rbenv "$command" $argv
  end
```

Here is what I think `rbenv` should look like, please comment if you think this is not enough and why!

If you think this is good you can patch yourself and redo the PR, or I can PR your plugin, whichever you prefer.

```fish
function init --on-event init_rbenv
  set -gx RBENV_SHELL fish
  if status --is-interactive
    source (rbenv init - | psub)
  end
end
```

**Comment by hauleth** [comment]
Now seems to work. Pushed to mine repo.

--
Łukasz Niemier <lukasz@niemier.pl>
http://lukasz.niemier.pl

2015-05-26 22:02 GMT+02:00 Jorge Bucaran <notifications@github.com>:

**Comment by bucaran** [comment]
Looks good man! Thanks!

**Pull request merged**
