### PR TITLE
Create dircolors.fish

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by bucaran** [comment]
I think this kind of code would go better in your custom `.dotfiles`. Don't you think so?

**Comment by hauleth** [comment]
This is only loader for custom `.dir_color` as Fish doesn't do this by default. 

--
Łukasz Jan Niemier

Dnia 25 maj 2015 o godz. 04:35 Jorge Bucaran <notifications@github.com> napisał(a):

**Comment by bucaran** [comment]
Exactly, this is something that either the framework itself should do (what do you think?) or the user put in his custom `.dotfiles`, having a package for this just feels a little off. That is just my opinion. I am trying to build software that is useful to everyone here, so if you think otherwise, please explain why you think so! :smile:

**Comment by hauleth** [comment]
I just was extracting functionalities that I had in my `config.fish` into plugins. It could be done by fish itself or by Wahoo but neither of them has that. So do as you please.

**Comment by bucaran** [comment]
I think this belongs to the framework. Now, how that should be implemented is a different thing. Will definitely work on this ASAP.

What are other configuration we should take care of loading? If you have any ideas please post them in #6.

Closing for now.

**Comment by hauleth** [comment]
You can add it as a default plugin (just like wa).

**Comment by bucaran** [comment]
Yes, it could be a package, something like `conf`, we do want to stay lean to speed up booting process.

**Pull request closed without merging**
